# Generated by Django 3.2.4 on 2021-06-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mob',
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
